# Generated by Django 3.2.5 on 2021-12-16 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=500)),
                ('session_date', models.DateField()),
                ('duration', models.DurationField()),
                ('start_time', models.TimeField()),
                ('expire_date', models.DateTimeField()),
                ('number_machines', models.IntegerField()),
                ('type', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('FACETOFACE', 'Face To Face')], max_length=200)),
                ('class_number', models.IntegerField(null=True)),
                ('meet_link', models.CharField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='sessions')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
