# Generated by Django 3.2.5 on 2021-12-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifsessions', '0002_alter_certificationsession_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationsession',
            name='avatar',
            field=models.ImageField(blank=True, default='/uploads/images/avatar.jpg', null=True, upload_to='sessions'),
        ),
    ]
