# Generated by Django 3.2.5 on 2021-12-28 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certifsessions', '0003_alter_certificationsession_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationsession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificationsession',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='sessions'),
        ),
    ]
