# Generated by Django 3.2.5 on 2021-12-28 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certifsessions', '0004_auto_20211228_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('session_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifsessions.certificationsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
