# Generated by Django 3.2.5 on 2021-12-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifsessions', '0005_registerinsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinsession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
