# Generated by Django 3.2.5 on 2021-12-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifsessions', '0006_alter_registerinsession_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerinsession',
            old_name='session_name',
            new_name='session',
        ),
    ]
