# Generated by Django 3.2.5 on 2022-01-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifsessions', '0007_rename_session_name_registerinsession_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationsession',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
